config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages, except: [:new, :edit, :update]
  post '/new_message' => 'messages#create_from_lff_site'#, :defaults => { :format => :json }
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'posts#index'
  resources :posts
  get '/api/posts' => 'api_posts#index', :defaults => { :format => :json }
  get '/api/posts/:id' => 'api_posts#show', :defaults => { :format => :json }
  get '/api/posts/:id' => 'api_posts#show', :defaults => { :format => :json }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :timestamp, :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/PostsController.rb
# class Api::PostsController < ApplicationController
#   def index
#     #code
#   end
# end

app/controllers/api_posts_controller.rb
class ApiPostsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery :except => [:index, :show]
  def index
    @posts = Post.order(timestamp: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:username])

    devise_parameter_sanitizer.permit(:account_update, :keys => [:username])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => :create_from_lff_site
  protect_from_forgery :except => [:create_from_lff_site]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.order(created_at: :desc)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_lff_site
    puts params
    @message = Message.new
    @message.first_name = params[:first_name]
    @message.last_name = params[:last_name]
    @message.org_name = params[:org_name]
    @message.email = params[:email_address]
    @message.phone = params[:phone_number]
    @message.message = params[:message]

    if params[:extra_info].present?
      url = request.env["HTTP_REFERER"] + "?success=false"
      redirect_to url
    else
      if @message.save
        MessageMailer.new_message_notification(@message).deliver_now
        # msg = {:status => 'success'}
        url = request.env["HTTP_REFERER"] + "?success=true"
        redirect_to url
      else
        url = request.env["HTTP_REFERER"] + "?success=false"
        redirect_to url
      end
    end

  end


  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:first_name, :last_name, :org_name, :email, :phone, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(timestamp: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :timestamp, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LffAdmin</title>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/png" href="<%= asset_path('favicon.ico') %>" sizes="16x16">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">LFF Admin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="http://lefkofskyfoundation.com" target="_blank">Live Site</a>
          </li>
          <li>
            <a class="nav-link" href="http://lefkofskyfoundation.com/newsroom/" target="_blank">Newsroom</a>
          </li>
          <li>
            <a class="nav-link" href="/posts">Posts</a>
          </li>
          <li>
            <a class="nav-link" href="/messages">Messages</a>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if current_user.present? %>
            <% if current_user.username.present? %>
              <li class="nav-item"><a class="nav-link">Signed in as <%= current_user.username %></a></li>
            <% else %>
              <li class="nav-item"><a class="nav-link">Signed in as <%= current_user.email %></a></li>
            <% end %>
            <li class="nav-item"><a href="/users/edit" class="nav-link">Edit profile</a></li>
            <li class="nav-item"><a href="/users/sign_out" data-method="delete" class="nav-link">Sign out</a></li>
          <% else %>
            <li class="nav-item"><a href="/users/sign_in" class="nav-link">Sign in</a></li>
          <% end %>
        </ul>

      </div>
    </nav>
    <div class="container mt-3">
      <div class="row">
        <div class="col">
          <% if alert.present? %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
          <% if notice.present? %>
            <div class="alert alert-info  fade show" role="alert">
              <%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
    <footer></footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :message_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :message_last_name %>
  </div>

  <div class="field">
    <%= form.label :org_name %>
    <%= form.text_field :org_name, id: :message_org_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :message_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :message_phone %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :message_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<table class="table mt-5">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Org name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Received at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.first_name %></td>
        <td><%= message.last_name %></td>
        <td><%= message.org_name %></td>
        <td><%= message.email %></td>
        <td><%= message.phone %></td>
        <td><%= message.created_at.strftime("%l:%M%p on %b %e, %Y") %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @message.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @message.last_name %>
</p>

<p>
  <strong>Org name:</strong>
  <%= @message.org_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @message.phone %>
</p>

<p>
  <strong>Received at:</strong>
  <%= @message.created_at.strftime("%l:%M%p on %b %e, %Y") %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<%= link_to 'Back', messages_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: 'mt-4') do |form| %>
  <% if post.errors.any? %>
    <% post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :timestamp %><br>  
    <%= form.date_select :timestamp, id: :post_timestamp, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.cktext_area :content, id: :post_content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<a class="btn btn-success" href="<%= new_post_path %>">Add new post</a>

<table class="table mt-5">
  <thead>
    <tr>
      <th>Title</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.timestamp %></td>
        <td><%= link_to 'View', post, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @post.timestamp %>
</p>

<p>
  <strong>Content:</strong>
  <%= sanitize @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>